apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tadamon
spec:
  selector:
    matchLabels:
      app: tadamon-mautic 
  serviceName: "tadamon-service"
  replicas: 1 
  template:
    metadata:
      labels:
        app: tadamon-mautic 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tadamon-container
        image: nginx
        env:
        - name: MAUTIC_DB_USER
          value: "tadamon_user"
        - name: MAUTIC_DB_PASSWORD
          value: "123456789"
        - name: MAUTIC_DB_NAME
          value: "tadamon"
        - name: MAUTIC_DB_HOST
          value: "db.internal"
        - name: client-name
          value: "tadamon"        
        ports:
        - containerPort: 80
          name: tadamon
        volumeMounts:
        - name: tadamon-claim
          mountPath: /code      
        tty: true
        workingDir: /code
      restartPolicy: Always          
  volumeClaimTemplates:
  - metadata:
      name: tadamon-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 10Gi  