apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ CLIENT_NAME }}
spec:
  selector:
    matchLabels:
      app: {{ CLIENT_NAME }}
  serviceName: {{ CLIENT_NAME }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ CLIENT_NAME }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ CLIENT_NAME }}-mailhog
          image: mailhog/mailhog
          ports:
            - name: smtp-port
              containerPort: 1025
              protocol: TCP
            - name: http-port
              containerPort: 8025
              protocol: TCP
          env:
            - name: MH_UI_WEB_PATH
              value: mailhog
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always      
      - name: {{ CLIENT_NAME }}
        image: {{ IMAGE_NAME }}
        resources:
          limits:
            memory: {{ MEMORY }}
            cpu: {{ CPU }}
        env:
        - name: SITE_URL
          value: "https://{{ CLIENT_NAME }}.{{ DOMAIN_NAME }}"
        - name: MAUTIC_DB_HOST
          value: {{ DB_HOST }}
        - name: MAUTIC_DB_USER
          value: {{ CLIENT_NAME }}
        - name: MAUTIC_DB_PASSWORD
          value: {{ DB_PASSWORD }}
        - name: MAUTIC_DB_NAME
          value: {{ CLIENT_NAME }}
        - name: ADMIN_FIRST_NAME
          value: {{ ADMIN_FIRST_NAME }}
        - name: ADMIN_LAST_NAME
          value: {{ ADMIN_LAST_NAME }}
        - name: ADMIN_EMAIL
          value: {{ ADMIN_EMAIL }}
        - name: ADMIN_PASSWORD
          value: {{ ADMIN_PASSWORD }}
        ports:
        - containerPort: 80
          name: {{ CLIENT_NAME }}
        volumeMounts:
        - name: {{ CLIENT_NAME }}
          mountPath: /code
        tty: true
        workingDir: /code
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: {{ CLIENT_NAME }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi