apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: { CLIENT_NAME }
spec:
  selector:
    matchLabels:
      app: { CLIENT_NAME } 
  serviceName: { CLIENT_NAME }
  replicas: 1 
  template:
    metadata:
      labels:
        app: { CLIENT_NAME } 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: { CLIENT_NAME }
        image: nginx     
        ports:
        - containerPort: 80
          name: { CLIENT_NAME }
      restartPolicy: Always