apiVersion: v1
kind: Service
metadata:
  name: {{ CLIENT_NAME }}
  namespace: default
  labels:
    app: {{ CLIENT_NAME }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      name: smtp-http-port
      port: 8025
      targetPort: 8025      
  selector:
    app: {{ CLIENT_NAME }}
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack