apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: { CLIENT_NAME }
  namespace: default
spec:
  dnsNames:
    - { CLIENT_NAME }.steercampaign.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-ingress
  secretName: { CLIENT_NAME }