apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ CLIENT_NAME }}
  namespace: default
spec:
  dnsNames:
    - {{ CLIENT_NAME }}.{{ DOMAIN_NAME }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-ingress
  secretName: {{ CLIENT_NAME }}