apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ CLIENT_NAME }}
  namespace: default
  resourceVersion: '15703471'
spec:
  dnsNames:
    - {{ CUSTOM_DOMAIN }}
    - {{ CLIENT_NAME }}.{{ DOMAIN_NAME }}    
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-ingress
  secretName: {{ CLIENT_NAME }}