spec:
  tls:
    - hosts:
        - {{ DOMAIN_NAME }}      
  rules:
    - host: {{ DOMAIN_NAME }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ CLIENT_NAME }}
                port:
                  number: 80