apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ CLIENT_NAME }}
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: lock-{{ CLIENT_NAME }}
    nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"    