apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ CLIENT_NAME }}
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-ingress
    nginx.ingress.kubernetes.io/auth-realm: Enter your credentials
    nginx.ingress.kubernetes.io/auth-secret: {{ SECRET_NAME}}
    nginx.ingress.kubernetes.io/auth-secret-type: auth-map
    nginx.ingress.kubernetes.io/auth-type: basic