name: Test
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
env:
  PORT: 3333
  HOST: 0.0.0.0
  NODE_ENV: test
  APP_KEY: TU0ek-AcW9NoEi3Sy0m4B0vuGq_9xVOT
  ASSETS_DRIVER: fake
  SESSION_DRIVER: memory
  DRIVE_DISK: local
  K8S_API_URL: https://0c839694b0426bf3afe0aceae6c821ef.yl4.ap-south-1.eks.amazonaws.com
  K8S_CLUSTER_NAME: 'SteerCampaignDev'
  DEPLOY_DOMAIN_NAME: steercampaign.net
  ALB_DNS: a91db86aaa6a947ae8cf9a0ee09c740a-1073567115.ap-south-1.elb.amazonaws.com
  AWS_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  DB_HOST: 127.0.0.1
  DB_USERNAME: root
  DB_PASSWORD: ""  
  

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        commands: ['lint', 'test', 'coverage']
    name: ${{ matrix.commands }}
    services:
      db:
        image: mariadb:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db          
        ports:
          - 3306:3306        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Deps
        run: npm ci
        
      - name: Run ${{ matrix.commands }}
        env: 
          DB_PORT: ${{ job.services.db.ports['3306'] }}      
        run: |
          if [[ "${{ matrix.commands }}" == "lint" ]]; then
            npm run lint
          elif [[ "${{ matrix.commands }}" == "test" ]]; then
            npm run test
          elif [[ "${{ matrix.commands }}" == "coverage" ]]; then
            npm run coverage
          else
            echo "Invalid command"
            exit 1
          fi

  coversall:
    runs-on: ubuntu-latest
    needs: tests
    name: 'Coversall'
    services:
      db:
        image: mariadb:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db          
        ports:
          - 3306:3306        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Deps
      run: npm ci
    - name: build      
      run: |
          npm run build --if-present
          npm run lcov

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}